# Generated by Django 6.0.6 on 2026-08-22 14:25

import apps.oauth2_server.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "redirect_uris",
                    models.TextField(
                        help_text="One redirect URI per line. Must match exactly what the client sends."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.oauth2_server.models.generate_auth_code,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("redirect_uri", models.CharField(max_length=500)),
                ("code_challenge", models.CharField(max_length=200)),
                (
                    "code_challenge_method",
                    models.CharField(default="S256", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oauth2_server.oauthclient",
                    ),
                ),
            ],
        ),
    ]
