"""
apps/map_layers/management/commands/generate_layer_models.py

Reads layer_schema.json (produced by discover_layer_schema) and writes a
models.py with ONE real Django model per layer, each with correctly-typed
fields (CharField/IntegerField/FloatField/etc.) - not a JSON blob.

All generated models inherit from BaseMapFeature, which carries the shared
editing/tracking fields (geom, version, needs_review, updated_by, ...).

Usage:
    python manage.py generate_layer_models layer_schema.json --out apps/map_layers/models.py

Review the generated file before committing - shapefile field names are
often cryptic (10-char DBF limit, e.g. "NAME_UZ", "MAXSPEED") and you may
want to rename them or add choices= for enum-like fields (fclass, type).
"""

import json
import re

from django.core.management.base import BaseCommand, CommandError

DJANGO_TYPE_MAP = {
    "integer": "models.IntegerField(null=True, blank=True)",
    "float": "models.FloatField(null=True, blank=True)",
    "string": "models.CharField(max_length=255, null=True, blank=True)",
    "date": "models.DateField(null=True, blank=True)",
    "datetime": "models.DateTimeField(null=True, blank=True)",
    "time": "models.TimeField(null=True, blank=True)",
}

BASE_MODEL_SOURCE = '''
class BaseMapFeature(models.Model):
    """
    Shared editing/tracking fields for every generated layer model.
    Concrete subclasses (one per source layer) add their own typed columns.
    """
    geom = gis_models.GeometryField(srid=4326)
    source = models.CharField(max_length=50, default="nextgis")
    version = models.PositiveIntegerField(default=1)
    needs_review = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True,
        on_delete=models.SET_NULL, related_name="+",
    )

    class Meta:
        abstract = True
'''

FILE_HEADER = '''"""
apps/map_layers/models.py

AUTO-GENERATED by generate_layer_models from layer_schema.json.
Review before use - especially field names/types and any enum-like
columns (fclass, type, highway, ...) that might deserve choices=.

Regenerating will NOT touch models you've hand-edited unless you rerun
this command over them - keep the schema JSON and this file in version
control so you can see the diff.
"""

from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.db import models

'''


class Command(BaseCommand):
    help = "Generate one Django model per layer from a layer_schema.json file."

    def add_arguments(self, parser):
        parser.add_argument("schema_json", type=str)
        parser.add_argument("--out", type=str, default="generated_models.py")

    def handle(self, *args, **options):
        schema_path = options["schema_json"]
        out_path = options["out"]

        try:
            with open(schema_path, "r", encoding="utf-8") as f:
                schema = json.load(f)
        except FileNotFoundError:
            raise CommandError(f"Schema file not found: {schema_path}")

        chunks = [FILE_HEADER, BASE_MODEL_SOURCE]
        model_names = []

        for layer_name, layer_def in schema.items():
            class_name = self._class_name(layer_name)
            model_names.append((layer_name, class_name))
            chunks.append(self._render_model(class_name, layer_def))

        # Registry mapping so the import command can find the right model
        # for a given source layer name without guessing.
        chunks.append("\n\nLAYER_MODEL_MAP = {\n")
        for layer_name, class_name in model_names:
            chunks.append(f'    "{layer_name}": {class_name},\n')
        chunks.append("}\n")

        with open(out_path, "w", encoding="utf-8") as f:
            f.write("\n".join(chunks))

        self.stdout.write(self.style.SUCCESS(f"Generated {len(model_names)} models -> {out_path}"))
        self.stdout.write("Next: review the file, copy it over apps/map_layers/models.py, then:")
        self.stdout.write("  python manage.py makemigrations map_layers")
        self.stdout.write("  python manage.py migrate")

    def _render_model(self, class_name, layer_def):
        lines = [f"\n\nclass {class_name}(BaseMapFeature):"]
        fields = layer_def.get("fields", [])
        if not fields:
            lines.append("    pass")
        for field in fields:
            field_name = self._field_name(field["name"])
            django_field = DJANGO_TYPE_MAP.get(field["django_type"], DJANGO_TYPE_MAP["string"])
            lines.append(f"    {field_name} = {django_field}")
        lines.append("\n    class Meta:")
        lines.append(f'        verbose_name = "{class_name}"')
        return "\n".join(lines)

    @staticmethod
    def _class_name(layer_name):
        # e.g. "admin_boundaries" -> "AdminBoundaries"
        parts = re.split(r"[^0-9a-zA-Z]+", layer_name)
        return "".join(p.capitalize() for p in parts if p) or "UnnamedLayer"

    @staticmethod
    def _field_name(raw_name):
        # Sanitize DBF/shapefile column names into valid, lowercase Python
        # identifiers (they're sometimes truncated/cryptic, e.g. "NAME_UZ").
        name = raw_name.strip().lower()
        name = re.sub(r"[^0-9a-z_]", "_", name)
        if not name or name[0].isdigit():
            name = f"f_{name}"
        # avoid clobbering Django's implicit `id` and our own tracking fields
        if name in ("id", "geom", "source", "version", "needs_review",
                     "created_at", "updated_at", "updated_by"):
            name = f"attr_{name}"
        return name