# Generated by Django 6.0.6 on 2026-09-01 06:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AerialwayLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("aerialway", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "aerialway_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AerialwayPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("aerialway", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "aerialway_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AirportLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("length", models.CharField(blank=True, null=True)),
                ("ref", models.CharField(blank=True, null=True)),
                ("width", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "airport_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AirportPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("aerod_type", models.CharField(blank=True, null=True)),
                ("closest_to", models.CharField(blank=True, null=True)),
                ("icao", models.CharField(blank=True, null=True)),
                ("iata", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "airport_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl10",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl10",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl2",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl3",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl3",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl4",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl4",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl5",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl5",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl6",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl6",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl7",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl7",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl8",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("admin_lvl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l1", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l2d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l2", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l3d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l3", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l4d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l4", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l5d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l5", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l6d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l6", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l7d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l7", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l8d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l8", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l9d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l9", models.CharField(blank=True, max_length=128, null=True)),
                ("admin_l10d", models.BigIntegerField(blank=True, null=True)),
                ("admin_l10", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl8",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("building", models.CharField(blank=True, null=True)),
                ("addr_city", models.CharField(blank=True, null=True)),
                ("a_strt", models.CharField(blank=True, null=True)),
                ("a_sbrb", models.CharField(blank=True, null=True)),
                ("a_hsnmbr", models.CharField(blank=True, null=True)),
                ("a_place", models.CharField(blank=True, null=True)),
                ("a_pstcd", models.CharField(blank=True, null=True)),
                ("b_levels", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "building_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("building", models.CharField(blank=True, null=True)),
                ("addr_city", models.CharField(blank=True, null=True)),
                ("a_strt", models.CharField(blank=True, null=True)),
                ("a_sbrb", models.CharField(blank=True, null=True)),
                ("a_hsnmbr", models.CharField(blank=True, null=True)),
                ("a_place", models.CharField(blank=True, null=True)),
                ("a_pstcd", models.CharField(blank=True, null=True)),
                ("b_levels", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "building_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CutlineLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("cutline", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "cutline_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ElevationLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("natural", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "elevation_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ElevationPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("natural", models.CharField(blank=True, null=True)),
                ("ele", models.CharField(blank=True, null=True)),
                ("mountain_p", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "elevation_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HighwayCrossingPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("highway", models.CharField(blank=True, null=True)),
                ("crossing", models.CharField(blank=True, null=True)),
                ("crossing_r", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "highway_crossing_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HighwayLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("ref", models.CharField(blank=True, null=True)),
                ("highway", models.CharField(blank=True, null=True)),
                ("oneway", models.CharField(blank=True, null=True)),
                ("bridge", models.CharField(blank=True, null=True)),
                ("tunnel", models.CharField(blank=True, null=True)),
                ("maxspeed", models.CharField(blank=True, null=True)),
                ("lanes", models.CharField(blank=True, null=True)),
                ("width", models.CharField(blank=True, null=True)),
                ("surface", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "highway_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IslandPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("type", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "island_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Land",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "land",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandusePolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("landuse", models.CharField(blank=True, null=True)),
                ("rsdntl", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "landuse_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MilestonePoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("distance", models.CharField(blank=True, null=True)),
                ("source", models.CharField(blank=True, null=True)),
                ("check_date", models.CharField(blank=True, null=True)),
                ("pk_bkwrd", models.CharField(blank=True, null=True)),
                ("dist_bkwrd", models.CharField(blank=True, null=True)),
                ("dist_frwrd", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "milestone_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="NatureReservePolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("leisure", models.CharField(blank=True, null=True)),
                ("boundary", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "nature_reserve_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("fee", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("parking", models.CharField(blank=True, null=True)),
                ("access", models.CharField(blank=True, null=True)),
                ("capacity", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "parking_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("substance", models.CharField(blank=True, null=True)),
                ("location", models.CharField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, null=True)),
                ("diameter", models.CharField(blank=True, null=True)),
                ("pressure", models.CharField(blank=True, null=True)),
                ("capacity", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "pipeline_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoiPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("man_made", models.CharField(blank=True, null=True)),
                ("leisure", models.CharField(blank=True, null=True)),
                ("amenity", models.CharField(blank=True, null=True)),
                ("office", models.CharField(blank=True, null=True)),
                ("shop", models.CharField(blank=True, null=True)),
                ("tourism", models.CharField(blank=True, null=True)),
                ("sport", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "poi_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoiPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("man_made", models.CharField(blank=True, null=True)),
                ("leisure", models.CharField(blank=True, null=True)),
                ("amenity", models.CharField(blank=True, null=True)),
                ("office", models.CharField(blank=True, null=True)),
                ("shop", models.CharField(blank=True, null=True)),
                ("tourism", models.CharField(blank=True, null=True)),
                ("sport", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "poi_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PortPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "port_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PortPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "port_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PowerLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("power", models.CharField(blank=True, null=True)),
                ("voltage", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "power_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PowerPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("power", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "power_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicTransportLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("route", models.CharField(blank=True, null=True)),
                ("ref", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                (
                    "from_field",
                    models.CharField(blank=True, db_column="from", null=True),
                ),
                ("to", models.CharField(blank=True, null=True)),
                ("via", models.CharField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, null=True)),
                ("network", models.CharField(blank=True, null=True)),
                ("note", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "public_transport_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicTransportPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("railway", models.CharField(blank=True, null=True)),
                ("highway", models.CharField(blank=True, null=True)),
                ("ref", models.CharField(blank=True, null=True)),
                ("network", models.CharField(blank=True, null=True)),
                ("public_tra", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "public_transport_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RailwayLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("railway", models.CharField(blank=True, null=True)),
                ("gauge", models.CharField(blank=True, null=True)),
                ("service", models.CharField(blank=True, null=True)),
                ("bridge", models.CharField(blank=True, null=True)),
                ("tunnel", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "railway_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RailwayPlatformPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("railway", models.CharField(blank=True, null=True)),
                ("ref", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "railway_platform_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RailwayStationPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("railway", models.CharField(blank=True, null=True)),
                ("station", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "railway_station_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SettlementPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("int_name", models.CharField(blank=True, null=True)),
                ("official_s", models.CharField(blank=True, null=True)),
                ("place", models.CharField(blank=True, null=True)),
                ("a_cntr", models.CharField(blank=True, null=True)),
                ("a_rgn", models.CharField(blank=True, null=True)),
                ("a_dstrct", models.CharField(blank=True, null=True)),
                ("a_pstcd", models.CharField(blank=True, null=True)),
                ("population", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "settlement_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SettlementPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("int_name", models.CharField(blank=True, null=True)),
                ("official_s", models.CharField(blank=True, null=True)),
                ("place", models.CharField(blank=True, null=True)),
                ("a_cntr", models.CharField(blank=True, null=True)),
                ("a_rgn", models.CharField(blank=True, null=True)),
                ("a_dstrct", models.CharField(blank=True, null=True)),
                ("a_pstcd", models.CharField(blank=True, null=True)),
                ("population", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "db_table": "settlement_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubwayEntrancePoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("railway", models.CharField(blank=True, null=True)),
                ("network", models.CharField(blank=True, null=True)),
                ("operator", models.CharField(blank=True, null=True)),
                ("ref", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "subway_entrance_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SurfacePolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("natural", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "surface_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VegetationPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("natural", models.CharField(blank=True, null=True)),
                ("landuse", models.CharField(blank=True, null=True)),
                ("wood", models.CharField(blank=True, null=True)),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "vegetation_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WaterLine",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("waterway", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "water_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WaterPoint",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("natural", models.CharField(blank=True, null=True)),
                ("waterway", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "water_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WaterPolygon",
            fields=[
                (
                    "edit_source",
                    models.CharField(
                        db_column="edit_source", default="nextgis", max_length=50
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("needs_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, null=True)),
                ("name_en", models.CharField(blank=True, null=True)),
                ("natural", models.CharField(blank=True, null=True)),
                ("waterway", models.CharField(blank=True, null=True)),
                ("wetland", models.CharField(blank=True, null=True)),
                ("osm_type", models.CharField(blank=True, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "water_polygon",
                "managed": False,
            },
        ),
    ]
