# Generated by Django 6.0.6 on 2026-08-26 09:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "geometry_type",
                    models.CharField(
                        help_text="Original geometry type reported by GDAL, e.g. 'Polygon', 'LineString', 'Point'.",
                        max_length=30,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="nextgis",
                        help_text="Where this layer's data originally came from.",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("visible_by_default", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MapFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("attrs", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(default="nextgis", max_length=50)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False,
                        help_text="Flag features known/suspected to be outdated, e.g. in remote regions pending a field survey.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_map_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="map_layers.maplayer",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["layer"], name="map_layers__layer_i_7edef4_idx"
                    ),
                    models.Index(
                        fields=["needs_review"], name="map_layers__needs_r_44d961_idx"
                    ),
                ],
            },
        ),
    ]
