# Generated by Django 6.0.6 on 2026-09-01 06:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("web_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OsmNode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.IntegerField(default=1)),
                ("visible", models.BooleanField(default=True)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "changeset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to="web_app.osmchangeset",
                    ),
                ),
            ],
            options={
                "db_table": "osm_nodes",
            },
        ),
        migrations.CreateModel(
            name="OsmNodeTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k", models.CharField(max_length=255)),
                ("v", models.TextField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_set",
                        to="id_editor.osmnode",
                    ),
                ),
            ],
            options={
                "db_table": "osm_node_tags",
            },
        ),
        migrations.CreateModel(
            name="OsmRelation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.IntegerField(default=1)),
                ("visible", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changeset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relations",
                        to="web_app.osmchangeset",
                    ),
                ),
            ],
            options={
                "db_table": "osm_relations",
            },
        ),
        migrations.CreateModel(
            name="OsmRelationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_id", models.IntegerField()),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("node", "node"),
                            ("way", "way"),
                            ("relation", "relation"),
                        ],
                        max_length=10,
                    ),
                ),
                ("member_id", models.BigIntegerField()),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="id_editor.osmrelation",
                    ),
                ),
            ],
            options={
                "db_table": "osm_relation_members",
                "ordering": ["sequence_id"],
            },
        ),
        migrations.CreateModel(
            name="OsmRelationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k", models.CharField(max_length=255)),
                ("v", models.TextField()),
                (
                    "relation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_set",
                        to="id_editor.osmrelation",
                    ),
                ),
            ],
            options={
                "db_table": "osm_relation_tags",
            },
        ),
        migrations.CreateModel(
            name="OsmWay",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("version", models.IntegerField(default=1)),
                ("visible", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changeset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ways",
                        to="web_app.osmchangeset",
                    ),
                ),
            ],
            options={
                "db_table": "osm_ways",
            },
        ),
        migrations.CreateModel(
            name="OsmWayNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_id", models.IntegerField()),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="id_editor.osmnode",
                    ),
                ),
                (
                    "way",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="way_nodes",
                        to="id_editor.osmway",
                    ),
                ),
            ],
            options={
                "db_table": "osm_way_nodes",
                "ordering": ["sequence_id"],
            },
        ),
        migrations.CreateModel(
            name="OsmWayTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k", models.CharField(max_length=255)),
                ("v", models.TextField()),
                (
                    "way",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags_set",
                        to="id_editor.osmway",
                    ),
                ),
            ],
            options={
                "db_table": "osm_way_tags",
            },
        ),
        migrations.AddIndex(
            model_name="osmnode",
            index=models.Index(fields=["visible"], name="osm_nodes_visible_3c3f98_idx"),
        ),
        migrations.AddIndex(
            model_name="osmnodetag",
            index=models.Index(fields=["node"], name="osm_node_ta_node_id_43c578_idx"),
        ),
        migrations.AddConstraint(
            model_name="osmnodetag",
            constraint=models.UniqueConstraint(
                fields=("node", "k"), name="uniq_node_tag_key"
            ),
        ),
        migrations.AddIndex(
            model_name="osmrelationmember",
            index=models.Index(
                fields=["relation", "sequence_id"],
                name="osm_relatio_relatio_bea586_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="osmrelationmember",
            index=models.Index(
                fields=["member_type", "member_id"],
                name="osm_relatio_member__f37cd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="osmrelationtag",
            index=models.Index(
                fields=["relation"], name="osm_relatio_relatio_84aad2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="osmrelationtag",
            constraint=models.UniqueConstraint(
                fields=("relation", "k"), name="uniq_relation_tag_key"
            ),
        ),
        migrations.AddIndex(
            model_name="osmwaynode",
            index=models.Index(
                fields=["way", "sequence_id"], name="osm_way_nod_way_id_ab8c0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="osmwaynode",
            index=models.Index(fields=["node"], name="osm_way_nod_node_id_c39677_idx"),
        ),
        migrations.AddConstraint(
            model_name="osmwaynode",
            constraint=models.UniqueConstraint(
                fields=("way", "sequence_id"), name="uniq_way_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="osmwaytag",
            index=models.Index(fields=["way"], name="osm_way_tag_way_id_b2164d_idx"),
        ),
        migrations.AddConstraint(
            model_name="osmwaytag",
            constraint=models.UniqueConstraint(
                fields=("way", "k"), name="uniq_way_tag_key"
            ),
        ),
    ]
