# Generated by Django 6.0.6 on 2026-09-01 06:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoundaryPolygonLvl2",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("admin_lvl", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl2",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl4",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("admin_lvl", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl4",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl6",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("admin_lvl", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl6",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoundaryPolygonLvl8",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("admin_lvl", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "boundary_polygon_lvl8",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BuildingPolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("building", models.CharField(blank=True, max_length=255, null=True)),
                ("a_strt", models.CharField(blank=True, max_length=255, null=True)),
                ("a_hsnmbr", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "building_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HighwayLine",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("ref", models.CharField(blank=True, max_length=255, null=True)),
                ("highway", models.CharField(blank=True, max_length=255, null=True)),
                ("oneway", models.CharField(blank=True, max_length=255, null=True)),
                ("bridge", models.CharField(blank=True, max_length=255, null=True)),
                ("tunnel", models.CharField(blank=True, max_length=255, null=True)),
                ("maxspeed", models.CharField(blank=True, max_length=50, null=True)),
                ("lanes", models.CharField(blank=True, max_length=50, null=True)),
                ("surface", models.CharField(blank=True, max_length=100, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "highway_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LandusePolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("landuse", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "landuse_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ParkingPolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("parking", models.CharField(blank=True, max_length=255, null=True)),
                ("access", models.CharField(blank=True, max_length=255, null=True)),
                ("capacity", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "parking_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoiPoint",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("man_made", models.CharField(blank=True, max_length=255, null=True)),
                ("leisure", models.CharField(blank=True, max_length=255, null=True)),
                ("amenity", models.CharField(blank=True, max_length=255, null=True)),
                ("office", models.CharField(blank=True, max_length=255, null=True)),
                ("shop", models.CharField(blank=True, max_length=255, null=True)),
                ("tourism", models.CharField(blank=True, max_length=255, null=True)),
                ("sport", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_type", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "poi_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoiPolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("man_made", models.CharField(blank=True, max_length=255, null=True)),
                ("leisure", models.CharField(blank=True, max_length=255, null=True)),
                ("amenity", models.CharField(blank=True, max_length=255, null=True)),
                ("office", models.CharField(blank=True, max_length=255, null=True)),
                ("shop", models.CharField(blank=True, max_length=255, null=True)),
                ("tourism", models.CharField(blank=True, max_length=255, null=True)),
                ("sport", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_type", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "poi_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RailwayLine",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("railway", models.CharField(blank=True, max_length=255, null=True)),
                ("bridge", models.CharField(blank=True, max_length=255, null=True)),
                ("tunnel", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "railway_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SettlementPoint",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("int_name", models.CharField(blank=True, max_length=255, null=True)),
                ("official_s", models.CharField(blank=True, max_length=255, null=True)),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                ("a_cntr", models.CharField(blank=True, max_length=255, null=True)),
                ("a_rgn", models.CharField(blank=True, max_length=255, null=True)),
                ("a_dstrct", models.CharField(blank=True, max_length=255, null=True)),
                ("a_pstcd", models.CharField(blank=True, max_length=255, null=True)),
                ("population", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_type", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "settlement_point",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SettlementPolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("int_name", models.CharField(blank=True, max_length=255, null=True)),
                ("official_s", models.CharField(blank=True, max_length=255, null=True)),
                ("place", models.CharField(blank=True, max_length=255, null=True)),
                ("a_cntr", models.CharField(blank=True, max_length=255, null=True)),
                ("a_rgn", models.CharField(blank=True, max_length=255, null=True)),
                ("a_dstrct", models.CharField(blank=True, max_length=255, null=True)),
                ("a_pstcd", models.CharField(blank=True, max_length=255, null=True)),
                ("population", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_type", models.CharField(blank=True, max_length=20, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "settlement_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VegetationPolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "vegetation_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WaterLine",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("waterway", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "water_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WaterPolygon",
            fields=[
                ("fid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("osm_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "water_polygon",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OsmChangeset",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user", models.CharField(default="anonymous", max_length=255)),
                ("uid", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("open", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "osm_changeset",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OsmMeta",
            fields=[
                ("osm_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("osm_type", models.CharField(default="node", max_length=20)),
                ("version", models.IntegerField(default=1)),
                ("uid", models.IntegerField(default=1)),
                ("user", models.CharField(default="anonymous", max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changeset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web_app.osmchangeset",
                    ),
                ),
            ],
            options={
                "db_table": "osm_meta",
                "managed": True,
            },
        ),
    ]
